INSERT INTO Musicas (ID, Musicas, Artista, Duracao, Idioma)
VALUES
(1, 'So it goes', 'Taylor swift', '03:27', 'ingles'),
(2, 'The archer', 'Taylor swift', '03:37', 'ingles'),
(3, 'You are in love', 'Taylor swift', '04:27', 'ingles'),
(4, 'All too well', 'Taylor swift', '10:13', 'ingles'),
(5, 'Epiphany', 'Taylor swift', '04:49', 'ingles'),
(6, 'Long live', 'Taylor swift', '05:19', 'ingles'),
(7, 'Would've, could've, should've', 'Taylor swift', '04:20', 'ingles'),
(8, 'Mine', 'Beyoncé', '06:18', 'ingles'),
(9, 'Already over', 'Sabrina Carpenter', '02:50', 'ingles'),
(10, 'Serendipity', 'BTS', '04:36', 'inglês/coreano'),
(11, 'Save me', 'BTS', '03:16', 'inglês/coreano'),
(12, 'Surreal', 'Luisa Sonza', '03:54', 'português'),
(13, 'We on', 'BTS', '03:50', 'ingles/coreano'),
(14, 'Satellite', 'Bebe Rexha', '03:28', 'ingles'),
(15, 'Run away', 'Tomorrow by together', '03:31', 'ingles/coreano'),
(16, 'Can’t you see me', 'Tomorrow by together', '03:21', 'ingles/coreano'),
(17, '0X1=lovesong', 'Tomorrow by together', '03:22', 'ingles/coreano'),
(18, 'Still', 'Dove Cameron', '03:09', 'ingles'),
(19, 'FRAGILE THINGS', 'Dove Cameron', '03:33', 'ingles'),
(20, 'Death row', 'Bebe Rexha', '03:00', 'ingles');
