INSERT INTO Musicas (ID, Musicas, Artista, Duracao, Idioma)
VALUES
(1,	'So it goes', 'Taylor swift', 'ingles' '03:27'),
(2,	'The archer', 'Taylor swift', 'ingles' '03:37'),
(3,	'You are in love', 'Taylor swift', 'ingles' '04:27'),
(4,	'All too well', 'Taylor swift', 'ingles' '10:13'),
(5,	'Epiphany', 'Taylor swift', 'ingles' '04:49'),
(6,	'Long live', 'Taylor swift', 'ingles' '05:19'),
(7,	'Would've, could've, should've', 'Taylor swift', 'ingles' '04:20'),
(8,	'Mine', 'Beyoncé', 'ingles' '06:18'),
(9,	'Already over', 'Sabrina Carpenter', 'ingles' '02:50'),
(10,	'Serendipity', 'BTS', 'inglês/coreano' '04:36'),
(11,	'Save me', 'BTS', 'inglês/coreano' '03:16'),
(12,	'Surreal', 'Luisa Sonza', 'português' '03:54'),
(13,	'We on', 'BTS', 'ingles/coreano' '03:50'),
(14,	'Satellite', 'Bebe Rexha', 'ingles' '03:28'),
(15,	'Run away', 'Tomorrow by together', 'ingles/coreano' '03:31'),
(16,	'Can’t you see me', 'Tomorrow by together', 'ingles/coreano' '03:21'),
(17,	'0X1=lovesong', 'Tomorrow by together', 'ingles/coreano' '03:22'),
(18,	'Still , 'Dove Cameron', 'ingles' '03:09'),
(19,	'FRAGILE THINGS', 'Dove Cameron', 'ingles' '03:33'),
(20,	'Death row', 'Bebe Rexha', 'ingles' '03:00'),
